using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using Injekko.Editor.GraphToolkit;
using Injekko.Unity;

namespace Injekko.Editor
{
	internal static class InjekGraphPlanCodeGenerator
	{
		internal const string GeneratedSourcePath = "Assets/Injekko/Generated/InjekkoGraphPlans.Generated.cs";

		internal static void GenerateAndWriteAll(bool refreshAssets)
		{
			var graphPlans = FindAllCompiledScopePlans();
			string generatedSource = GeneratePlansSource(graphPlans);
			WriteGeneratedSource(generatedSource, refreshAssets);
		}

		static IReadOnlyList<InjekCompiledScopePlan> FindAllCompiledScopePlans()
		{
			return AssetDatabase.FindAssets($"t:{nameof(InjekCompiledScopePlan)}")
				.Select(AssetDatabase.GUIDToAssetPath)
				.Where(static path => !string.IsNullOrWhiteSpace(path))
				.OrderBy(static path => path, StringComparer.Ordinal)
				.Select(static path => AssetDatabase.LoadAssetAtPath<InjekCompiledScopePlan>(path))
				.Where(static graphPlan => graphPlan != null)
				.ToArray();
		}

		static string GeneratePlansSource(IReadOnlyList<InjekCompiledScopePlan> graphPlans)
		{
			var builder = new StringBuilder();
			builder.AppendLine("// <auto-generated />");
			builder.AppendLine("namespace Injekko.Generated");
			builder.AppendLine("{");
			builder.AppendLine("\tinternal static class InjekkoGraphPlanBootstrap");
			builder.AppendLine("\t{");
			builder.AppendLine("\t\t[global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
			builder.AppendLine("\t\tstatic void Register()");
			builder.AppendLine("\t\t{");

			foreach (var graph in graphPlans
				.Where(static graph => graph != null && !string.IsNullOrWhiteSpace(graph.GraphId))
				.Distinct()
				.OrderBy(static graph => graph.GraphId, StringComparer.Ordinal))
			{
				string methodName = $"Apply_{SanitizeIdentifier(graph.GraphId)}";
				builder.AppendLine($"\t\t\tglobal::Injekko.Unity.InjekGeneratedRuntimeRegistry.RegisterGraphPlan(\"{Escape(graph.GraphId)}\", {methodName});");
			}

			builder.AppendLine("\t\t}");
			builder.AppendLine();

			foreach (var graph in graphPlans
				.Where(static graph => graph != null && !string.IsNullOrWhiteSpace(graph.GraphId))
				.Distinct()
				.OrderBy(static graph => graph.GraphId, StringComparer.Ordinal))
				AppendPlanMethod(builder, graph);

			builder.AppendLine("\t}");
			builder.AppendLine("}");
			return builder.ToString();
		}

		static void AppendPlanMethod(StringBuilder builder, InjekCompiledScopePlan graphPlan)
		{
			string methodName = $"Apply_{SanitizeIdentifier(graphPlan.GraphId)}";

			builder.AppendLine($"\t\tstatic void {methodName}(global::Injekko.Unity.IInjekGraphReferenceHost host, global::Injekko.Unity.InjekScopeNode scope)");
			builder.AppendLine("\t\t{");
			builder.AppendLine("\t\t\tif (host == null)");
			builder.AppendLine("\t\t\t\tthrow new global::System.ArgumentNullException(nameof(host));");
			builder.AppendLine("\t\t\tif (scope == null)");
			builder.AppendLine("\t\t\t\tthrow new global::System.ArgumentNullException(nameof(scope));");

			foreach (var node in graphPlan.BindingDefinitions.Select(InjekkoBindingAuthoringDefinition.FromCompiledDefinition))
			{
				foreach (var statement in BuildNodeStatements(node))
					builder.AppendLine($"\t\t\t{statement}");
			}

			builder.AppendLine("\t\t}");
			builder.AppendLine();
		}

		static IEnumerable<string> BuildNodeStatements(InjekkoBindingAuthoringDefinition node)
		{
			string serviceTypeName = BuildTypeName(node.ServiceType);
			string referenceAccess = $"host.GetGraphReferenceOrThrow(\"{Escape(node.ReferenceSlotId)}\")";

			// Graph plans stay intentionally direct here: resolve the serialized slot and bind the exact service type.
			if (node.Kind != InjekGraphNodeKind.BindInstance)
			{
				yield return $"throw new global::Injekko.InjekException(\"Graph plan '{Escape(node.DisplayName)}' contains unsupported binding kind '{node.Kind}' in the instance-first runtime path.\");";
				yield break;
			}

			if (!string.IsNullOrWhiteSpace(serviceTypeName) && !string.IsNullOrWhiteSpace(node.ReferenceSlotId))
				yield return $"scope.BindInstance(({serviceTypeName}){referenceAccess});";
		}

		static string BuildTypeName(Type type)
		{
			if (type == null)
				return string.Empty;

			string typeName = (type.FullName ?? type.Name).Replace("+", ".");
			return $"global::{typeName}";
		}

		static string SanitizeIdentifier(string value)
		{
			if (string.IsNullOrWhiteSpace(value))
				return "Unnamed";

			var builder = new StringBuilder(value.Length);
			foreach (char character in value)
				builder.Append(char.IsLetterOrDigit(character) ? character : '_');
			return builder.ToString();
		}

		static string Escape(string value)
			=> (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

		static void WriteGeneratedSource(string source, bool refreshAssets)
		{
			string fullDirectoryPath = Path.GetDirectoryName(GeneratedSourcePath);
			if (!string.IsNullOrWhiteSpace(fullDirectoryPath))
				Directory.CreateDirectory(fullDirectoryPath);

			string existing = File.Exists(GeneratedSourcePath) ? File.ReadAllText(GeneratedSourcePath) : string.Empty;
			if (string.Equals(existing, source, StringComparison.Ordinal))
				return;

			File.WriteAllText(GeneratedSourcePath, source);
			if (refreshAssets)
				AssetDatabase.Refresh();
		}
	}
}
